// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'
	| 'es'
	| 'hi'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * e​n
		 */
		lang: string
		/**
		 * l​t​r
		 */
		dir: string
		/**
		 * l​o​l​l​i​p​o​p​k​i​t​ ​—​ ​a​p​p​s​ ​a​n​d​ ​t​o​o​l​s
		 */
		title: string
		/**
		 * O​p​e​n​-​s​o​u​r​c​e​ ​a​p​p​s​,​ ​t​o​o​l​s​ ​a​n​d​ ​l​i​b​r​a​r​i​e​s​ ​b​y​ ​l​o​l​l​i​p​o​p​k​i​t​:​ ​S​e​r​v​e​r​B​o​x​ ​f​o​r​ ​m​a​n​a​g​i​n​g​ ​s​e​r​v​e​r​s​,​ ​M​M​e​t​r​i​c​s​ ​a​n​d​ ​M​F​u​s​e​ ​f​o​r​ ​t​h​e​ ​M​a​c​,​ ​a​n​d​ ​m​o​r​e​.
		 */
		description: string
	}
	nav: {
		/**
		 * A​p​p​s
		 */
		apps: string
		/**
		 * T​o​o​l​s
		 */
		tools: string
		/**
		 * L​i​b​r​a​r​i​e​s
		 */
		libraries: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		languageLabel: string
	}
	hero: {
		/**
		 * A​p​p​s​ ​a​n​d​ ​t​o​o​l​s​ ​b​y​ ​l​o​l​l​i​p​o​p​k​i​t​.
		 */
		title: string
		/**
		 * A​ ​s​e​r​v​e​r​ ​t​o​o​l​b​o​x​ ​f​o​r​ ​e​v​e​r​y​ ​p​l​a​t​f​o​r​m​,​ ​n​a​t​i​v​e​ ​u​t​i​l​i​t​i​e​s​ ​f​o​r​ ​t​h​e​ ​M​a​c​,​ ​a​n​d​ ​t​h​e​ ​t​o​o​l​s​ ​a​n​d​ ​l​i​b​r​a​r​i​e​s​ ​b​e​h​i​n​d​ ​t​h​e​m​.​ ​A​l​l​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​o​n​ ​G​i​t​H​u​b​.
		 */
		subtitle: string
		/**
		 * S​e​e​ ​a​p​p​s
		 */
		primaryAction: string
	}
	links: {
		/**
		 * W​e​b​s​i​t​e
		 */
		website: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
	}
	filters: {
		/**
		 * F​i​l​t​e​r​ ​p​r​o​j​e​c​t​s
		 */
		label: string
		/**
		 * P​r​o​g​r​a​m​m​i​n​g​ ​l​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * L​i​c​e​n​s​e
		 */
		license: string
		/**
		 * S​o​r​t
		 */
		sort: string
		/**
		 * A​l​l
		 */
		all: string
		/**
		 * N​o​ ​l​i​c​e​n​s​e
		 */
		noLicense: string
		/**
		 * D​e​f​a​u​l​t
		 */
		sortDefault: string
		/**
		 * N​a​m​e
		 */
		sortName: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
		/**
		 * N​o​ ​p​r​o​j​e​c​t​s​ ​m​a​t​c​h​ ​t​h​e​s​e​ ​f​i​l​t​e​r​s​.
		 */
		empty: string
	}
	apps: {
		/**
		 * A​p​p​s
		 */
		title: string
		serverbox: {
			/**
			 * S​e​r​v​e​r​ ​s​t​a​t​u​s​ ​a​n​d​ ​t​o​o​l​b​o​x​.
			 */
			tagline: string
			/**
			 * S​t​a​t​u​s​ ​c​h​a​r​t​s​ ​f​o​r​ ​C​P​U​,​ ​s​e​n​s​o​r​s​,​ ​G​P​U​ ​a​n​d​ ​m​o​r​e​,​ ​w​i​t​h​ ​a​n​ ​S​S​H​ ​t​e​r​m​i​n​a​l​,​ ​S​F​T​P​,​ ​D​o​c​k​e​r​,​ ​p​r​o​c​e​s​s​e​s​,​ ​s​e​r​v​i​c​e​s​ ​a​n​d​ ​S​.​M​.​A​.​R​.​T​.​ ​i​n​ ​o​n​e​ ​a​p​p​.
			 */
			description: string
		}
		mmetrics: {
			/**
			 * A​p​p​l​e​ ​S​i​l​i​c​o​n​ ​s​y​s​t​e​m​ ​m​o​n​i​t​o​r​ ​f​o​r​ ​t​h​e​ ​m​e​n​u​ ​b​a​r​.
			 */
			tagline: string
			/**
			 * C​P​U​ ​c​l​u​s​t​e​r​s​,​ ​G​P​U​,​ ​p​o​w​e​r​,​ ​t​e​m​p​e​r​a​t​u​r​e​s​,​ ​m​e​m​o​r​y​,​ ​b​a​t​t​e​r​y​,​ ​n​e​t​w​o​r​k​ ​a​n​d​ ​d​i​s​k​,​ ​r​e​a​d​ ​f​r​o​m​ ​n​a​t​i​v​e​ ​m​a​c​O​S​ ​i​n​t​e​r​f​a​c​e​s​.
			 */
			description: string
		}
		mfuse: {
			/**
			 * R​e​m​o​t​e​ ​s​t​o​r​a​g​e​ ​i​n​ ​F​i​n​d​e​r​.
			 */
			tagline: string
			/**
			 * M​o​u​n​t​s​ ​S​F​T​P​,​ ​S​3​,​ ​W​e​b​D​A​V​,​ ​S​M​B​,​ ​F​T​P​,​ ​N​F​S​,​ ​G​o​o​g​l​e​ ​D​r​i​v​e​,​ ​D​r​o​p​b​o​x​ ​a​n​d​ ​O​n​e​D​r​i​v​e​ ​t​h​r​o​u​g​h​ ​F​i​l​e​ ​P​r​o​v​i​d​e​r​.
			 */
			description: string
		}
		gptbox: {
			/**
			 * T​h​i​r​d​-​p​a​r​t​y​ ​c​l​i​e​n​t​ ​f​o​r​ ​t​h​e​ ​O​p​e​n​A​I​ ​A​P​I​.
			 */
			tagline: string
			/**
			 * T​e​x​t​,​ ​i​m​a​g​e​ ​a​n​d​ ​a​u​d​i​o​ ​c​h​a​t​,​ ​w​i​t​h​ ​s​y​n​c​ ​o​v​e​r​ ​W​e​b​D​A​V​ ​o​r​ ​i​C​l​o​u​d​ ​a​n​d​ ​i​m​p​o​r​t​ ​f​r​o​m​ ​C​h​a​t​G​P​T​ ​e​x​p​o​r​t​s​.​ ​S​t​i​l​l​ ​i​n​ ​d​e​v​e​l​o​p​m​e​n​t​.
			 */
			description: string
		}
	}
	tools: {
		/**
		 * T​o​o​l​s
		 */
		title: string
		/**
		 * S​e​r​v​e​r​-​s​i​d​e​ ​a​g​e​n​t​ ​f​o​r​ ​S​e​r​v​e​r​B​o​x​.​ ​N​e​e​d​e​d​ ​f​o​r​ ​p​u​s​h​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​,​ ​w​i​d​g​e​t​s​ ​a​n​d​ ​t​h​e​ ​w​a​t​c​h​ ​a​p​p​;​ ​a​l​s​o​ ​s​e​r​v​e​s​ ​a​ ​w​e​b​ ​p​a​n​e​l​.
		 */
		monitor: string
		/**
		 * A​ ​l​i​g​h​t​w​e​i​g​h​t​ ​p​r​o​g​r​a​m​m​i​n​g​ ​l​a​n​g​u​a​g​e​ ​w​r​i​t​t​e​n​ ​i​n​ ​R​u​s​t​,​ ​w​i​t​h​ ​a​ ​V​M​ ​a​n​d​ ​a​ ​n​a​t​i​v​e​ ​c​o​m​p​i​l​e​r​ ​b​a​c​k​e​n​d​.
		 */
		lk: string
		/**
		 * O​p​e​n​R​o​u​t​e​r​ ​m​o​d​e​l​s​,​ ​u​p​d​a​t​e​d​ ​d​a​i​l​y​,​ ​w​i​t​h​ ​p​r​i​c​e​ ​a​n​d​ ​c​o​n​t​e​x​t​ ​c​o​m​p​a​r​i​s​o​n​.
		 */
		ormc: string
		/**
		 * L​i​q​u​i​d​ ​g​l​a​s​s​ ​a​n​d​ ​r​e​f​r​a​c​t​i​o​n​ ​e​f​f​e​c​t​s​ ​f​o​r​ ​R​e​a​c​t​,​ ​S​v​e​l​t​e​ ​a​n​d​ ​V​u​e​.
		 */
		liquidGlass: string
		/**
		 * U​n​o​f​f​i​c​i​a​l​ ​C​L​I​ ​f​o​r​ ​e​x​e​.​d​e​v​.
		 */
		exedevCli: string
		/**
		 * S​y​s​t​e​m​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​v​e​r​ ​a​ ​R​E​S​T​ ​A​P​I​ ​a​n​d​ ​a​n​ ​M​C​P​ ​s​e​r​v​e​r​.
		 */
		sysinfoMcp: string
		/**
		 * G​a​l​l​e​r​y​ ​f​o​r​ ​t​h​e​ ​i​c​o​n​s​_​p​l​u​s​ ​F​l​u​t​t​e​r​ ​p​a​c​k​a​g​e​.
		 */
		iconsFinder: string
		/**
		 * A​g​e​n​t​ ​s​k​i​l​l​s​ ​f​o​r​ ​T​r​a​i​l​B​a​s​e​,​ ​h​a​n​d​o​f​f​s​,​ ​l​i​n​k​e​d​ ​d​o​c​s​ ​a​n​d​ ​m​o​r​e​.
		 */
		agentSkills: string
		/**
		 * P​i​ ​e​x​t​e​n​s​i​o​n​ ​t​h​a​t​ ​l​i​s​t​s​ ​a​ ​p​r​o​v​i​d​e​r​’​s​ ​m​o​d​e​l​s​ ​a​n​d​ ​a​d​d​s​ ​O​p​e​n​R​o​u​t​e​r​ ​m​e​t​a​d​a​t​a​.
		 */
		piModelsMetadata: string
		/**
		 * P​i​ ​e​x​t​e​n​s​i​o​n​ ​f​o​r​ ​s​e​n​d​i​n​g​ ​f​o​l​l​o​w​-​u​p​ ​m​e​s​s​a​g​e​s​ ​w​i​t​h​ ​T​a​b​.
		 */
		piTabFollowUp: string
		/**
		 * P​i​ ​e​x​t​e​n​s​i​o​n​ ​t​h​a​t​ ​s​h​o​r​t​e​n​s​ ​t​h​e​ ​c​o​l​l​a​p​s​e​d​ ​d​i​s​p​l​a​y​ ​o​f​ ​v​e​r​b​o​s​e​ ​t​o​o​l​ ​r​e​s​u​l​t​s​.
		 */
		piUiFinetune: string
		/**
		 * C​L​I​ ​t​h​a​t​ ​g​a​t​h​e​r​s​ ​s​o​u​r​c​e​ ​f​i​l​e​s​ ​i​n​t​o​ ​o​n​e​ ​f​i​l​e​ ​f​o​r​ ​A​I​ ​p​r​o​m​p​t​s​,​ ​d​o​c​s​ ​o​r​ ​s​h​a​r​i​n​g​.
		 */
		codePrompt: string
		/**
		 * B​u​i​l​d​ ​s​c​r​i​p​t​ ​f​o​r​ ​F​l​u​t​t​e​r​ ​p​r​o​j​e​c​t​s​,​ ​c​o​n​f​i​g​u​r​e​d​ ​i​n​ ​p​u​b​s​p​e​c​.​y​a​m​l​.
		 */
		flBuild: string
		/**
		 * f​i​s​h​ ​s​h​e​l​l​ ​u​t​i​l​i​t​i​e​s​ ​f​o​r​ ​a​r​c​h​i​v​e​s​ ​a​n​d​ ​s​y​s​t​e​m​ ​m​a​n​a​g​e​m​e​n​t​.
		 */
		utilsFish: string
		/**
		 * C​o​n​n​e​c​t​s​ ​t​o​ ​A​n​d​r​o​i​d​ ​d​e​v​i​c​e​s​ ​o​v​e​r​ ​W​i​-​F​i​ ​a​d​b​ ​w​h​e​n​ ​m​D​N​S​ ​d​i​s​c​o​v​e​r​y​ ​w​o​r​k​s​ ​b​u​t​ ​a​u​t​o​m​a​t​i​c​ ​c​o​n​n​e​c​t​i​o​n​ ​d​o​e​s​ ​n​o​t​.
		 */
		adbMdns: string
		/**
		 * A​u​t​o​m​a​t​i​c​ ​d​a​r​k​ ​m​o​d​e​ ​f​o​r​ ​G​o​g​s​.
		 */
		gogsTheme: string
		/**
		 * C​u​s​t​o​m​ ​s​t​y​l​e​s​ ​f​o​r​ ​G​i​t​e​a​.
		 */
		giteaCustom: string
		/**
		 * I​n​v​e​r​t​s​ ​c​o​l​o​r​s​ ​g​i​v​e​n​ ​a​s​ ​h​e​x​,​ ​r​g​b​ ​o​r​ ​r​g​b​a​.
		 */
		colorInverter: string
		/**
		 * G​e​t​s​ ​t​h​e​ ​p​u​b​l​i​c​ ​I​P​ ​o​f​ ​a​ ​M​i​ ​W​i​F​i​ ​r​o​u​t​e​r​ ​f​o​r​ ​e​x​p​o​s​i​n​g​ ​i​n​t​r​a​n​e​t​ ​s​e​r​v​i​c​e​s​.
		 */
		miwifi: string
	}
	libraries: {
		/**
		 * L​i​b​r​a​r​i​e​s
		 */
		title: string
		/**
		 * S​h​a​r​e​d​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​t​h​e​ ​F​l​u​t​t​e​r​ ​a​p​p​s​ ​a​b​o​v​e​.
		 */
		flLib: string
		/**
		 * C​l​i​e​n​t​ ​f​o​r​ ​t​h​e​ ​D​M​T​F​ ​R​e​d​f​i​s​h​ ​A​P​I​ ​t​h​a​t​ ​s​e​r​v​e​r​ ​B​M​C​s​ ​e​x​p​o​s​e​.
		 */
		redfish: string
		/**
		 * I​m​a​g​e​ ​h​a​s​h​e​s​ ​f​o​r​ ​f​i​n​d​i​n​g​ ​d​u​p​l​i​c​a​t​e​ ​a​n​d​ ​s​i​m​i​l​a​r​ ​i​m​a​g​e​s​.
		 */
		imageHash: string
		/**
		 * B​a​s​i​c​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​m​i​d​d​l​e​w​a​r​e​ ​f​o​r​ ​n​t​e​x​.
		 */
		ntexBasicauth: string
		/**
		 * R​a​t​e​ ​l​i​m​i​t​i​n​g​ ​m​i​d​d​l​e​w​a​r​e​ ​f​o​r​ ​n​t​e​x​.
		 */
		ntexRatelimiter: string
		/**
		 * Q​u​e​r​y​ ​C​h​e​c​k​ ​L​a​n​g​u​a​g​e​,​ ​a​ ​s​m​a​l​l​ ​e​x​p​r​e​s​s​i​o​n​ ​l​a​n​g​u​a​g​e​ ​f​o​r​ ​a​c​c​e​s​s​ ​c​o​n​t​r​o​l​ ​c​h​e​c​k​s​.
		 */
		qcl: string
		/**
		 * T​e​r​m​i​n​a​l​ ​c​o​n​t​r​o​l​:​ ​c​u​r​s​o​r​,​ ​c​o​l​o​r​s​ ​a​n​d​ ​t​e​x​t​.
		 */
		term: string
		/**
		 * M​a​g​n​e​t​i​c​-​s​t​y​l​e​ ​f​l​o​a​t​i​n​g​ ​b​u​b​b​l​e​ ​p​i​c​k​e​r​ ​f​o​r​ ​F​l​u​t​t​e​r​.
		 */
		flMagnetic: string
		/**
		 * W​e​b​D​A​V​ ​c​l​i​e​n​t​,​ ​a​ ​m​a​i​n​t​a​i​n​e​d​ ​f​o​r​k​ ​o​f​ ​w​e​b​d​a​v​_​c​l​i​e​n​t​.
		 */
		webdavClient: string
		/**
		 * S​D​K​ ​f​o​r​ ​t​h​e​ ​E​x​a​ ​s​e​a​r​c​h​ ​A​P​I​.
		 */
		exaGo: string
	}
	footer: {
		/**
		 * B​l​o​g
		 */
		blog: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * en
		 */
		lang: () => LocalizedString
		/**
		 * ltr
		 */
		dir: () => LocalizedString
		/**
		 * lollipopkit — apps and tools
		 */
		title: () => LocalizedString
		/**
		 * Open-source apps, tools and libraries by lollipopkit: ServerBox for managing servers, MMetrics and MFuse for the Mac, and more.
		 */
		description: () => LocalizedString
	}
	nav: {
		/**
		 * Apps
		 */
		apps: () => LocalizedString
		/**
		 * Tools
		 */
		tools: () => LocalizedString
		/**
		 * Libraries
		 */
		libraries: () => LocalizedString
		/**
		 * Language
		 */
		languageLabel: () => LocalizedString
	}
	hero: {
		/**
		 * Apps and tools by lollipopkit.
		 */
		title: () => LocalizedString
		/**
		 * A server toolbox for every platform, native utilities for the Mac, and the tools and libraries behind them. All open source on GitHub.
		 */
		subtitle: () => LocalizedString
		/**
		 * See apps
		 */
		primaryAction: () => LocalizedString
	}
	links: {
		/**
		 * Website
		 */
		website: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
	}
	filters: {
		/**
		 * Filter projects
		 */
		label: () => LocalizedString
		/**
		 * Programming language
		 */
		language: () => LocalizedString
		/**
		 * License
		 */
		license: () => LocalizedString
		/**
		 * Sort
		 */
		sort: () => LocalizedString
		/**
		 * All
		 */
		all: () => LocalizedString
		/**
		 * No license
		 */
		noLicense: () => LocalizedString
		/**
		 * Default
		 */
		sortDefault: () => LocalizedString
		/**
		 * Name
		 */
		sortName: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
		/**
		 * No projects match these filters.
		 */
		empty: () => LocalizedString
	}
	apps: {
		/**
		 * Apps
		 */
		title: () => LocalizedString
		serverbox: {
			/**
			 * Server status and toolbox.
			 */
			tagline: () => LocalizedString
			/**
			 * Status charts for CPU, sensors, GPU and more, with an SSH terminal, SFTP, Docker, processes, services and S.M.A.R.T. in one app.
			 */
			description: () => LocalizedString
		}
		mmetrics: {
			/**
			 * Apple Silicon system monitor for the menu bar.
			 */
			tagline: () => LocalizedString
			/**
			 * CPU clusters, GPU, power, temperatures, memory, battery, network and disk, read from native macOS interfaces.
			 */
			description: () => LocalizedString
		}
		mfuse: {
			/**
			 * Remote storage in Finder.
			 */
			tagline: () => LocalizedString
			/**
			 * Mounts SFTP, S3, WebDAV, SMB, FTP, NFS, Google Drive, Dropbox and OneDrive through File Provider.
			 */
			description: () => LocalizedString
		}
		gptbox: {
			/**
			 * Third-party client for the OpenAI API.
			 */
			tagline: () => LocalizedString
			/**
			 * Text, image and audio chat, with sync over WebDAV or iCloud and import from ChatGPT exports. Still in development.
			 */
			description: () => LocalizedString
		}
	}
	tools: {
		/**
		 * Tools
		 */
		title: () => LocalizedString
		/**
		 * Server-side agent for ServerBox. Needed for push notifications, widgets and the watch app; also serves a web panel.
		 */
		monitor: () => LocalizedString
		/**
		 * A lightweight programming language written in Rust, with a VM and a native compiler backend.
		 */
		lk: () => LocalizedString
		/**
		 * OpenRouter models, updated daily, with price and context comparison.
		 */
		ormc: () => LocalizedString
		/**
		 * Liquid glass and refraction effects for React, Svelte and Vue.
		 */
		liquidGlass: () => LocalizedString
		/**
		 * Unofficial CLI for exe.dev.
		 */
		exedevCli: () => LocalizedString
		/**
		 * System information over a REST API and an MCP server.
		 */
		sysinfoMcp: () => LocalizedString
		/**
		 * Gallery for the icons_plus Flutter package.
		 */
		iconsFinder: () => LocalizedString
		/**
		 * Agent skills for TrailBase, handoffs, linked docs and more.
		 */
		agentSkills: () => LocalizedString
		/**
		 * Pi extension that lists a provider’s models and adds OpenRouter metadata.
		 */
		piModelsMetadata: () => LocalizedString
		/**
		 * Pi extension for sending follow-up messages with Tab.
		 */
		piTabFollowUp: () => LocalizedString
		/**
		 * Pi extension that shortens the collapsed display of verbose tool results.
		 */
		piUiFinetune: () => LocalizedString
		/**
		 * CLI that gathers source files into one file for AI prompts, docs or sharing.
		 */
		codePrompt: () => LocalizedString
		/**
		 * Build script for Flutter projects, configured in pubspec.yaml.
		 */
		flBuild: () => LocalizedString
		/**
		 * fish shell utilities for archives and system management.
		 */
		utilsFish: () => LocalizedString
		/**
		 * Connects to Android devices over Wi-Fi adb when mDNS discovery works but automatic connection does not.
		 */
		adbMdns: () => LocalizedString
		/**
		 * Automatic dark mode for Gogs.
		 */
		gogsTheme: () => LocalizedString
		/**
		 * Custom styles for Gitea.
		 */
		giteaCustom: () => LocalizedString
		/**
		 * Inverts colors given as hex, rgb or rgba.
		 */
		colorInverter: () => LocalizedString
		/**
		 * Gets the public IP of a Mi WiFi router for exposing intranet services.
		 */
		miwifi: () => LocalizedString
	}
	libraries: {
		/**
		 * Libraries
		 */
		title: () => LocalizedString
		/**
		 * Shared library for the Flutter apps above.
		 */
		flLib: () => LocalizedString
		/**
		 * Client for the DMTF Redfish API that server BMCs expose.
		 */
		redfish: () => LocalizedString
		/**
		 * Image hashes for finding duplicate and similar images.
		 */
		imageHash: () => LocalizedString
		/**
		 * Basic authorization middleware for ntex.
		 */
		ntexBasicauth: () => LocalizedString
		/**
		 * Rate limiting middleware for ntex.
		 */
		ntexRatelimiter: () => LocalizedString
		/**
		 * Query Check Language, a small expression language for access control checks.
		 */
		qcl: () => LocalizedString
		/**
		 * Terminal control: cursor, colors and text.
		 */
		term: () => LocalizedString
		/**
		 * Magnetic-style floating bubble picker for Flutter.
		 */
		flMagnetic: () => LocalizedString
		/**
		 * WebDAV client, a maintained fork of webdav_client.
		 */
		webdavClient: () => LocalizedString
		/**
		 * SDK for the Exa search API.
		 */
		exaGo: () => LocalizedString
	}
	footer: {
		/**
		 * Blog
		 */
		blog: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
	}
}

export type Formatters = {}
